name: Test Code

on:
  workflow_dispatch:
  repository_dispatch:
    types: [fts]

jobs:
  fts:
    runs-on: ubuntu-latest
    steps:
      - name: start
        env:
          KEY_S: ${{ secrets.KEY_S }}
          KEY_W: ${{ secrets.KEY_W }}

        run: |
          docker -h
